'use client';

import { Bot, LoaderCircle, Sparkles } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Badge, Button, Card, CardHeader } from '@/components/ui';
import { useGscWorkspace } from './gsc-context';
import { searchTypeLabel } from './live-workspaces';

function renderBrief(text: string) {
  const sections: Array<{ title: string; body: string[] }> = [];
  let current = { title: 'AI改善ブリーフ', body: [] as string[] };
  for (const line of text.split('\n')) {
    if (line.startsWith('### ')) {
      if (current.body.length) sections.push(current);
      current = { title: line.slice(4).trim(), body: [] };
    } else if (line.trim()) current.body.push(line.trim());
  }
  if (current.body.length) sections.push(current);
  return sections;
}

export function AiOpportunityAssistant() {
  const workspace = useGscWorkspace();
  const opportunities = workspace.analysis?.opportunities ?? [];
  const [selected, setSelected] = useState('');
  const [brief, setBrief] = useState('');
  const [model, setModel] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (!opportunities.length) { setSelected(''); return; }
    if (!opportunities.some((item) => item.id === selected)) setSelected(opportunities[0].id);
  }, [opportunities, selected]);

  useEffect(() => { setBrief(''); setError(''); setModel(''); }, [workspace.searchType, workspace.selectedSite]);

  const current = useMemo(() => opportunities.find((item) => item.id === selected), [opportunities, selected]);
  if (!workspace.analysis || !opportunities.length) return null;

  const generate = async () => {
    if (!selected) return;
    setLoading(true);
    setError('');
    setBrief('');
    try {
      const response = await fetch('/api/gsc/ai-brief', {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ site: workspace.selectedSite, opportunityId: selected, days: workspace.days, device: workspace.device, searchType: workspace.searchType, thresholds: workspace.thresholds }),
      });
      const data = await response.json() as { brief?: string; model?: string; error?: string; configured?: boolean };
      if (!response.ok) {
        if (data.configured === false) throw new Error('OPENAI_API_KEYを設定するとAI改善ブリーフを利用できます。通常のGSC分析はこの設定なしで動作します。');
        throw new Error(data.error || 'AI改善ブリーフの生成に失敗しました。');
      }
      setBrief(data.brief ?? '');
      setModel(data.model ?? '');
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : 'AI改善ブリーフの生成に失敗しました。');
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="p4-ai-card">
      <CardHeader title="AI改善ブリーフ" description={`${searchTypeLabel(workspace.searchType)}のGSC数値だけを根拠に、原因仮説・確認項目・改善案・成功判定を整理します`} action={<Badge tone="info">OPTIONAL</Badge>} />
      <div className="p4-ai-controls"><label><span>分析するOpportunity</span><select value={selected} onChange={(event) => { setSelected(event.target.value); setBrief(''); setError(''); }}>{opportunities.slice(0, 60).map((item) => <option value={item.id} key={item.id}>{item.score} / {item.type} / {item.target}</option>)}</select></label><Button icon={loading ? <LoaderCircle className="p4-spin" /> : <Sparkles />} disabled={loading || !selected} onClick={() => void generate()}>{loading ? '分析中' : '改善ブリーフ生成'}</Button></div>
      {current && <div className="p4-ai-target"><Bot /><span><strong>{current.title}</strong><code>{current.target}</code><small>{searchTypeLabel(workspace.searchType)} / Score {current.score} / Impact {current.impact} / Effort {current.effort}</small></span></div>}
      {error && <div className="p4-ai-error">{error}</div>}
      {brief && <div className="p4-ai-result"><div className="p4-ai-result__meta"><Bot /><span>Generated by {model || 'AI'}</span><small>検索結果・ページ本文は未参照。GSCデータ上の仮説です。</small></div><div className="p4-ai-sections">{renderBrief(brief).map((section) => <section key={section.title}><h3>{section.title}</h3>{section.body.map((line, index) => <p key={`${section.title}-${index}`}>{line}</p>)}</section>)}</div></div>}
    </Card>
  );
}
